apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      {{- end }}
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName  | quote }}
      {{- end }}
      serviceAccountName: {{ template "name" . }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        {{- range $arg := .Values.args }}
        - {{ $arg }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
        {{- if .Values.metrics.enabled }}
        - name: metrics
          containerPort: 8080
        {{- end }}
        {{- if .Values.health.enabled }}
        - name: health
          containerPort: 8088
        livenessProbe:
          httpGet:
            path: /livez
            port: health
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
        {{- end }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        {{- if .Values.tlsSecret }}
        volumeMounts:
        - mountPath: /tls
          name: tls
          readOnly: true
        {{- end}}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tlsSecret }}
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: {{ .Values.tlsSecret }}
      {{- end}}