---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: xgql-testing
---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: xgql-testing
  annotations:
    kubernetes.io/service-account.name: "xgql-testing"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xgql-testing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-admin
subjects:
- kind: ServiceAccount
  namespace: default
  name: xgql-testing